services:
  - type: web
    name: dentists-assistant-frontend
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
      # Create necessary directories
      mkdir -p .next/standalone/.next/static
      mkdir -p .next/standalone/public
      # Copy the standalone server and its dependencies
      cp -r .next/standalone/* .next/standalone/
      # Copy the .next directory contents
      cp -r .next/static/* .next/standalone/.next/static/
      cp -r .next/server .next/standalone/.next/
      cp -r .next/required-server-files.json .next/standalone/.next/
      cp -r .next/build-manifest.json .next/standalone/.next/
      cp -r .next/prerender-manifest.json .next/standalone/.next/
      cp -r .next/routes-manifest.json .next/standalone/.next/
      # Copy public assets
      cp -r public/* .next/standalone/public/
      # Ensure package.json is in the standalone directory
      cp package.json .next/standalone/
    startCommand: cd .next/standalone && HOSTNAME=0.0.0.0 node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_API_URL
        value: https://dentists-assistant-ai-backend.onrender.com
      - key: FRONTEND_URL
        value: https://dentists-assistant-ai-frontend.onrender.com
    autoDeploy: true

  - type: web
    name: dentists-assistant-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://dentists-assistant-ai-frontend.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
