services:
  - type: web
    name: dentists-assistant-frontend
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
      mkdir -p .next/standalone/.next
      # Copy the entire .next directory
      cp -r .next/* .next/standalone/.next/
      # Copy standalone files
      cp -r .next/standalone/* .next/standalone/
      # Ensure static files are in place
      mkdir -p .next/standalone/.next/static
      cp -r .next/static/* .next/standalone/.next/static/
      # Copy public directory
      cp -r public .next/standalone/
    startCommand: cd frontend/.next/standalone && NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOSTNAME
        value: 0.0.0.0
      - key: PORT
        sync: true
      - key: NEXT_PUBLIC_API_URL
        value: https://dentists-assistant-ai-backend.onrender.com
      - key: FRONTEND_URL
        value: https://dentists-assistant-ai-frontend.onrender.com
    autoDeploy: true

  - type: web
    name: dentists-assistant-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && PORT=$PORT node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: true
      - key: FRONTEND_URL
        value: https://dentists-assistant-ai-frontend.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
