services:
  # Backend API Service
  - type: web
    name: dentists-assistant-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        fromService:
          name: dentists-assistant-frontend
          type: static
          property: url
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Static Site
  - type: static
    name: dentists-assistant-frontend
    buildCommand: cd frontend && npm install && npm run build
    distDir: frontend/out
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: dentists-assistant-backend
          type: web
          property: url
    autoDeploy: true 