services:
  - type: web
    name: dentists-assistant-frontend
    env: node
    buildCommand: |
      cd frontend
      echo "=== Environment Information ==="
      echo "Node version: $(node -v)"
      echo "NPM version: $(npm -v)"
      echo "Current directory: $(pwd)"
      
      echo "=== Starting build process ==="
      npm install
      npm run build
      
      echo "=== Debug: Checking build output ==="
      ls -la .next/
      
      echo "=== Preparing standalone build ==="
      # Clean up any existing standalone directory
      rm -rf .next/standalone
      
      echo "=== Copying standalone output ==="
      # Copy the entire standalone output first
      cp -r .next/standalone .next/standalone_temp
      
      # Create fresh standalone directory
      mkdir -p .next/standalone/.next
      
      # Copy server.js and other root files
      cp .next/standalone_temp/* .next/standalone/ 2>/dev/null || true
      
      # Copy the .next directory contents
      cp -r .next/static .next/standalone/.next/
      cp -r .next/server .next/standalone/.next/
      cp -r .next/standalone_temp/.next/* .next/standalone/.next/ 2>/dev/null || true
      
      # Copy public directory and package.json
      cp -r public .next/standalone/
      cp package.json .next/standalone/
      
      # Clean up temp directory
      rm -rf .next/standalone_temp
      
      echo "=== Setting permissions ==="
      chmod -R 755 .next/standalone
      
      echo "=== Verifying final structure ==="
      echo "Root standalone directory:"
      ls -la .next/standalone/
      echo ".next directory:"
      ls -la .next/standalone/.next/
      echo "Checking for server.js:"
      ls -la .next/standalone/server.js || echo "WARNING: server.js not found!"
      
      echo "=== Build completed ==="
    startCommand: |
      cd frontend/.next/standalone
      echo "=== Server Environment Check ==="
      echo "PORT: $PORT"
      echo "NODE_ENV: $NODE_ENV"
      echo "HOSTNAME: $HOSTNAME"
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      
      # Ensure port is explicitly set in process
      export PORT=10000
      export HOSTNAME=0.0.0.0
      
      echo "=== Starting Next.js Server ==="
      NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: NEXT_PUBLIC_API_URL
        value: https://dentists-assistant-ai-backend.onrender.com
      - key: FRONTEND_URL
        value: https://dentists-assistant-ai-frontend.onrender.com
    autoDeploy: true

  - type: web
    name: dentists-assistant-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: FRONTEND_URL
        value: https://dentists-assistant-ai-frontend.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
